name: Build conda docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate or nightly builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml
  pull_request:
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release')) }}

jobs:
  build-docker:
    runs-on: linux.12xlarge
    strategy:
      matrix:
        cuda_version: ["11.8", "12.1", "12.4", "cpu"]
    env:
      CUDA_VERSION: ${{ matrix.cuda_version }}
    steps:
      - name: Clone PyTorch
        uses: actions/checkout@v3
        with:
          path: pytorch
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        if: ${{ inputs.aws-role-to-assume != '' }}
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-session-name: gha-linux-build
          role-duration-seconds: 10800
          aws-region: us-east-1
      - name: Calculate docker image
        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
        with:
          docker-image-name: pytorch-linux-focal-cuda12.1-cudnn9-py3-gcc9
          working-directory: pytorch
