name: Build conda docker images

on:
  workflow_dispatch:
    inputs:
        docker-image-name:
          description: 'Name of the Docker image'
          required: true 
  push:
    branches:
      - main
      - release/*
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate or nightly builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml
  pull_request:
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release')) }}

jobs:
  build-docker:
    runs-on: linux.12xlarge
    strategy:
      matrix:
        cuda_version: ["11.8", "12.1", "12.4", "cpu"]
    env:
      CUDA_VERSION: ${{ matrix.cuda_version }}
    steps:
      - name: Clone PyTorch
        uses: actions/checkout@v3
        with:
          path: pytorch
      - name: Calculate docker image
        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
        with:
            docker-image-name: ${{ inputs.docker-image }}
      - name: Build Docker Image
        run: |
          pytorch/pytorch/.ci/docker/build_docker_conda.sh
